--local lsp = require('lsp-zero').preset({})
--
--lsp.ensure_installed({
--	--'tsserver',
--	--'html',
--	--'jsonls',
--	--'emmet_ls',
--	--'sqlls',
--	--'tailwindcss',
--	--'prettier',
--})

--require('lspconfig').lua_ls.setup(lsp.nvim_lua_ls())
--lsp.setup()
--<C-y> to confirm emmet
